### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by drinking-code** [drinking-code/cherry-soda#3]
Tracking plans for cherry-cola.

## Stability & Flexibility
Cherry-cola has to become stable with all the current features. 

- [ ] Dynamic code synchronisation (DOM)
  - [ ] Text content
  - [ ] Attributes
  - [ ] Element types
  - [ ] Wrapping / unwrapping elements (moving the other elements horizontally)
  - [ ] Appending / prepending elements (moving the other elements vertically)
- [ ] Stable client side element finder (DOM tracking) [low priority]
- [ ] Assigning multiple elements to a single ref [testing]
- [ ] Lexical scope extraction as a function, give file and target position, and (target) function with lexical scope is extracted and bundled
  - [ ] For `doSomething()` callbacks
  - [ ] For state `.use()` callbacks
- [ ] Complete document elements (html (?), head, body) components
- [ ] Full CLI (dev, build, start)

## Performance 
- [ ] Leverage Bun's APIs (instead of relying on the polyfills)
- [ ] Analyse and optimise compiler timeline and communication between different components of the compiler
- [ ] Optimise the style plugin for imports to compile css (and scss, sass) module names without using sass
- [ ] Test for rendering performance
- [ ] Focus on page load (perceived) performance

## Features
- [ ] Deferring `sideEffect()` results
- [ ] Routing (and location, response codes)
- [ ] CSS splitting and deferring
- [ ] Islands
  - [ ] Island priority
  - [ ] Scrollable islands (infinite scrolling with predefined content)
- [ ] Component / module lazy loading (code splitting)
- [ ] Images
  - [ ] Image component (automatic responsive images)
  - [ ] Image generation (favicon, thumbnails / rich link image)
- [ ] Static site generation
- [ ] Tool for analysing site load performance
- [ ] Full client site automatic app version manager
- [ ] Boilerplate generator

**Comment by drinking-code** [comment]
Edit to list after reimplementation:
- States are not bound to types anymore, to type switching is not a problem anymore
- Dynamic code synchronisation implementation was thrown out; has to be reimplemented
- Refs fundamentally have the ability to store multiple elements → mature this feature
- `doSomething()` works differently now; it is compiled by going through files; should be rewritten so that the lexical scope of the function is extracted with babel when it is called and compiled into a callable module, similar to state usage callbacks.
